using MailArchiver.Models;
using Microsoft.Extensions.Options;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using System.Text;

namespace MailArchiver.Services.ImapServer
{
    /// <summary>
    /// A fake SMTP server that accepts connections and pretends to send emails
    /// but silently discards everything. This keeps Apple Mail happy without
    /// needing real SMTP credentials for read-only archive accounts.
    ///
    /// Supports:
    ///   - Plain-text SMTP on SmtpPort (default 25) with optional STARTTLS
    ///   - Implicit-TLS SMTPS on SmtpsPort (default 465) for Apple Mail
    /// </summary>
    public class FakeSmtpService : BackgroundService
    {
        private readonly ImapServerOptions _options;
        private readonly ILogger<FakeSmtpService> _logger;

        // Shared TLS certificate — loaded from the file that ImapServerService exports
        private X509Certificate2? _tlsCertificate;

        public FakeSmtpService(
            IOptions<ImapServerOptions> options,
            ILogger<FakeSmtpService> logger)
        {
            _options = options.Value;
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            if (!_options.Enabled || !_options.SmtpEnabled)
            {
                _logger.LogInformation("Built-in fake SMTP server is disabled.");
                return;
            }

            // Wait a moment for ImapServerService to generate the certificate
            await Task.Delay(2000, stoppingToken);

            // Try to load the TLS certificate (same one generated by ImapServerService)
            _tlsCertificate = LoadOrGenerateCertificate();

            var bindAddress = IPAddress.Parse(_options.Host);
            var tasks = new List<Task>();

            // Plain-text SMTP listener
            if (_options.SmtpPort > 0)
            {
                tasks.Add(RunSmtpListener(bindAddress, _options.SmtpPort, useTls: false, stoppingToken));
            }

            // Implicit-TLS SMTPS listener
            if (_options.SmtpsPort > 0 && _tlsCertificate != null)
            {
                tasks.Add(RunSmtpListener(bindAddress, _options.SmtpsPort, useTls: true, stoppingToken));
            }

            try
            {
                await Task.WhenAll(tasks);
            }
            finally
            {
                _tlsCertificate?.Dispose();
            }
        }

        private X509Certificate2? LoadOrGenerateCertificate()
        {
            // Try to load the shared server cert exported by ImapServerService (same CA)
            var sharedPath = _options.ServerCertExportPath;
            for (int attempt = 0; attempt < 10; attempt++)
            {
                if (File.Exists(sharedPath))
                {
                    try
                    {
                        var cert = new X509Certificate2(
                            sharedPath,
                            (string?)null,
                            X509KeyStorageFlags.EphemeralKeySet);
                        _logger.LogInformation("Fake SMTP loaded shared server certificate from {Path}", sharedPath);
                        return cert;
                    }
                    catch (Exception ex)
                    {
                        _logger.LogWarning(ex, "Failed to load shared server cert from {Path}", sharedPath);
                    }
                }
                // Wait for ImapServerService to generate it
                Thread.Sleep(1000);
            }

            // Fallback: try custom cert path
            if (!string.IsNullOrWhiteSpace(_options.TlsCertificatePath) && File.Exists(_options.TlsCertificatePath))
            {
                try
                {
                    return new X509Certificate2(
                        _options.TlsCertificatePath,
                        _options.TlsCertificatePassword,
                        X509KeyStorageFlags.EphemeralKeySet);
                }
                catch { }
            }

            _logger.LogWarning("No TLS certificate available for fake SMTP — SMTPS will be disabled");
            return null;
        }

        private async Task RunSmtpListener(IPAddress bindAddress, int port, bool useTls, CancellationToken ct)
        {
            var listener = new TcpListener(bindAddress, port);
            listener.Start();

            var label = useTls ? "SMTPS (implicit TLS)" : "SMTP (plain)";
            _logger.LogInformation("Fake {Label} server started on {Host}:{Port} — accepts all mail, sends nothing.",
                label, _options.Host, port);

            try
            {
                while (!ct.IsCancellationRequested)
                {
                    TcpClient client;
                    try { client = await listener.AcceptTcpClientAsync(ct); }
                    catch (OperationCanceledException) { break; }
                    catch (Exception ex) { _logger.LogWarning(ex, "Fake SMTP accept error on port {Port}", port); continue; }

                    _ = Task.Run(async () =>
                    {
                        if (useTls)
                            await HandleTlsClientAsync(client, ct);
                        else
                            await HandleClientAsync(client, ct);
                    }, ct);
                }
            }
            finally { listener.Stop(); }
        }

        private async Task HandleTlsClientAsync(TcpClient client, CancellationToken ct)
        {
            var remoteEp = client.Client.RemoteEndPoint?.ToString() ?? "unknown";
            try
            {
                using (client)
                {
                    var sslStream = new SslStream(client.GetStream(), false);
                    await sslStream.AuthenticateAsServerAsync(new SslServerAuthenticationOptions
                    {
                        ServerCertificate = _tlsCertificate,
                        EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13,
                        ClientCertificateRequired = false,
                        CertificateRevocationCheckMode = X509RevocationMode.NoCheck
                    }, ct);

                    await HandleSmtpSession(sslStream, remoteEp, ct);
                }
            }
            catch (AuthenticationException ex)
            {
                _logger.LogDebug("Fake SMTPS TLS handshake failed from {Remote}: {Error}", remoteEp, ex.Message);
                client.Close();
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                _logger.LogDebug("Fake SMTPS session error from {Remote}: {Error}", remoteEp, ex.Message);
            }
        }

        private async Task HandleClientAsync(TcpClient client, CancellationToken ct)
        {
            var remoteEp = client.Client.RemoteEndPoint?.ToString() ?? "unknown";
            _logger.LogDebug("Fake SMTP connection from {Remote}", remoteEp);

            try
            {
                using (client)
                {
                    await HandleSmtpSession(client.GetStream(), remoteEp, ct);
                }
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                _logger.LogDebug("Fake SMTP session error from {Remote}: {Error}", remoteEp, ex.Message);
            }
        }

        private async Task HandleSmtpSession(Stream stream, string remoteEp, CancellationToken ct)
        {
            _logger.LogDebug("Fake SMTP session from {Remote}", remoteEp);

            await using (stream)
            {
                    var reader = new StreamReader(stream, Encoding.UTF8);
                    var writer = new StreamWriter(stream, Encoding.UTF8) { AutoFlush = true };

                    // SMTP greeting
                    await writer.WriteLineAsync("220 mailarchiver ESMTP Fake SMTP Ready");

                    bool inData = false;

                    while (!ct.IsCancellationRequested)
                    {
                        var line = await reader.ReadLineAsync(ct);
                        if (line == null) break;

                        _logger.LogDebug("SMTP << {Line}", line);

                        if (inData)
                        {
                            // In DATA mode, wait for the lone "." to end the message
                            if (line == ".")
                            {
                                inData = false;
                                await writer.WriteLineAsync("250 2.0.0 Ok: message discarded (archive is read-only)");
                            }
                            // Otherwise just consume the line silently
                            continue;
                        }

                        var upper = line.Trim().ToUpperInvariant();

                        if (upper.StartsWith("EHLO") || upper.StartsWith("HELO"))
                        {
                            await writer.WriteLineAsync("250-mailarchiver Hello");
                            await writer.WriteLineAsync("250-AUTH PLAIN LOGIN");
                            await writer.WriteLineAsync("250-SIZE 52428800");
                            await writer.WriteLineAsync("250 OK");
                        }
                        else if (upper.StartsWith("AUTH"))
                        {
                            // Accept any authentication attempt
                            if (upper.Contains("PLAIN"))
                            {
                                // Could be inline or next line
                                var parts = line.Trim().Split(' ');
                                if (parts.Length >= 3)
                                {
                                    // Inline auth: AUTH PLAIN <base64>
                                    await writer.WriteLineAsync("235 2.7.0 Authentication successful");
                                }
                                else
                                {
                                    // Need continuation
                                    await writer.WriteLineAsync("334 ");
                                    await reader.ReadLineAsync(ct); // consume the base64
                                    await writer.WriteLineAsync("235 2.7.0 Authentication successful");
                                }
                            }
                            else if (upper.Contains("LOGIN"))
                            {
                                await writer.WriteLineAsync("334 " + Convert.ToBase64String(Encoding.UTF8.GetBytes("Username:")));
                                await reader.ReadLineAsync(ct); // consume username
                                await writer.WriteLineAsync("334 " + Convert.ToBase64String(Encoding.UTF8.GetBytes("Password:")));
                                await reader.ReadLineAsync(ct); // consume password
                                await writer.WriteLineAsync("235 2.7.0 Authentication successful");
                            }
                            else
                            {
                                await writer.WriteLineAsync("235 2.7.0 Authentication successful");
                            }
                        }
                        else if (upper.StartsWith("MAIL FROM"))
                        {
                            await writer.WriteLineAsync("250 2.1.0 Ok");
                        }
                        else if (upper.StartsWith("RCPT TO"))
                        {
                            await writer.WriteLineAsync("250 2.1.5 Ok");
                        }
                        else if (upper.StartsWith("DATA"))
                        {
                            await writer.WriteLineAsync("354 End data with <CR><LF>.<CR><LF>");
                            inData = true;
                        }
                        else if (upper.StartsWith("QUIT"))
                        {
                            await writer.WriteLineAsync("221 2.0.0 Bye");
                            break;
                        }
                        else if (upper.StartsWith("NOOP"))
                        {
                            await writer.WriteLineAsync("250 2.0.0 Ok");
                        }
                        else if (upper.StartsWith("RSET"))
                        {
                            await writer.WriteLineAsync("250 2.0.0 Ok");
                        }
                        else if (upper.StartsWith("STARTTLS"))
                        {
                            // We don't support STARTTLS on plain SMTP — use SMTPS (port 465) instead
                            await writer.WriteLineAsync("454 4.7.0 TLS not available — use port 465 for implicit TLS");
                        }
                        else
                        {
                            await writer.WriteLineAsync("250 2.0.0 Ok");
                        }
                    }
            }
        }
    }
}
